### ISSUE TITLE
[Refactor] 마이 탭 리팩토링 및 기능 추가

### ISSUE THREAD

**Issue by seonyoung42** [finder-dev/finder_iOS#11]
## TODO
- [ ] RxSwift 적용
- [ ] viewModel 생성
- [ ] subView 생성해서 VC 정리
- [ ] UI Layout 수정
- [ ] 네트워크 로직 수정(서버 오픈 시 수정)
