### ISSUE TITLE
[Refactor] SignUpView 리팩토링

### ISSUE THREAD

**Issue by seonyoung42** [finder-dev/finder_iOS#7]
## TODO
- [ ] RxSwift 적용
- [ ] ViewModel 생성
- [ ] Subview 생성해서 VC 정리
- [ ] UI Layout 수정
- [ ] 코드 개선
- [ ] 네트워크 로직 수정(추후 서버 오픈되면 수정)
