### ISSUE TITLE
[Refactor] DebateView 리팩토링 및 기능 추가

### ISSUE THREAD

**Issue by seonyoung42** [finder-dev/finder_iOS#8]
## TODO
- [ ] RxSwift 적용
- [ ] viewModel 생성
- [ ] subView 생성해서 VC 단순화
- [ ] UI Layout 수정
- [ ] 토론 네이밍 debate로 통일
- [ ] 대댓글 기능 추가
- [ ] 네트워크 로직 수정(서버 오픈 시 수정)
