### ISSUE TITLE
[Refactor] 커뮤니티 탭 리팩토링 및 기능 추가

### ISSUE THREAD

**Issue by seonyoung42** [finder-dev/finder_iOS#9]
## TODO
- [x] RxSwift 적용
- [x] viewModel 생성
- [x] subView 생성해서 VC 정리
- [x] UI Layout 수정
- [ ] 네트워크 로직 수정(서버 오픈 시 수정)
